config/routes.rb
Rails.application.routes.draw do
  #トップページ
  root to: 'toppages#index'
  
  #ユーザ登録関連
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #ログイン/ログアウト関連
  get 'signup', to: 'users#new'

  #ユーザ詳細　追加情報関連
  get 'users/help', to: 'users#help', as: 'help'
  get 'items/register', to:'items#item_register_url', as: 'item_register_url'
  post 'items/register', to:'items#item_register_info', as: 'item_register_info'
  
  resources :items, only:[:new, :show, :create]
  resources :users, only:[:show, :new, :create, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  post 'users/:id', to: 'items#bulk_create', as: 'bulk_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
										uniqueness: { case_sensitive: false }

	has_many :ownerships
	has_many :ownership_items, through: :ownerships, source: :item

	has_secure_password
	
	#お気に入り登録用メソッド
	def want(item)
		self.ownerships.find_or_create_by(item_id: item.id)
	end
	
	def unwant(item)
		item = self.ownerships.find_by(item_id: item.id)
		item.destroy if item
	end
	
	def want?(item)
		self.ownership_items.include?(item)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      
      #セッション情報を設定
      session[:user_id] = @user.id
      
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def show
    #before_action
    @items = @user.ownership_items.page(params[:page]).per(5)
  end
  
  def edit
    #before_action
  end
  
  def update
    #before_action

    if @user.update(user_params) && params[:user][:password] != "" && params[:user][:password_confirmation] != ""
      flash[:success] = "登録情報を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = "登録情報の更新が出来ませんでした"
      render :edit
    end
  end
  
  def destroy
    #before_action
    
    @user.destroy
    
    flash[:success] = "登録情報を削除しました"
    session[:user_id] = nil
    redirect_to root_url
  end
  
  def help
    render :layout => 'help_layout'
  end

  private

  def set_params
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
	end
	
	def latest_price_display(item)
		results = Item.where(code: item.code)
		a = []
		
		results.each do |result|
			a << result.price.to_i
		end
		item_price = number_to_currency(a.last, :locale => 'ja')
		return item_price
	end
	
	def comparing_price(item)
		results = Item.where(code: item.code)
		a = []
		
		results.each do |result|
			a << result.price.to_i
		end
		
		a  = a.last(2)
		
		#初回登録時に比較用にデータを設定する
		if a.count == 1
			a << a[0]
		end
		
		if a[0] > a[1]
			#最新価格の方が安い場合
			return 0
		elsif a[0] < a[1]
			#最新価格の方が高い場合
			return 1
		end
	end
	
	#最安値を出すメソッド
	#このメソッドは使用していない。
	def lower_price_display(item)
		results = Item.where(code: item.code)
		a = []
		
		results.each do |result|
			a << result.price.to_i
		end
		
		#item_price = a.min
		item_price = number_to_currency(a.min, :locale => 'ja')
		#item_price = number_to_currency(a.min, :unit => "￥", :precision => 0)
		#item_price = number_to_currency(a.min)
		#binding.pry
		return item_price
	end
end

app/views/users/_form.html.erb
<div class="panel-body">
	<%= form_for(user) do |f| %>
		<div class="form-group">
			<%= f.label :name, 'お名前' %>
			<%= f.text_field :name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :email, 'メールアドレス' %>
			<%= f.email_field :email, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :password, 'パスワード' %>
			<%= f.password_field :password, class:"form-control" %>
		</div>
		
		<div class="form-group">
			<%= f.label :password_confirmation, 'パスワード（確認）' %>
			<%= f.password_field :password_confirmation, class:"form-control" %>
		</div>
		
		<div class="text-right">
			<%= f.submit '登録', class:"btn btn-success" %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
	
	<div class="col-xs-offset-1 col-xs-3">
		<div class="user-profile">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="icon text-center">
						<img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
					</div>
				</div>
				<div class="panel-footer panel-custom">
					<div class="text-center">
						<h4><%= @user.name %>さん</h4>
					</div>
				</div>
			</div>
		</div>
		<p>アバター画像はGravatarを使っています</br>登録は<a href="https://ja.gravatar.com/" target="_blank">こちら</a>から</p>
	</div>








	<div class="col-xs-6">
		<div class="panel panel-default">
			<div class="panel-heading">ユーザ編集</div>
			<%= render 'layouts/error_messages', message: @user %>
			
			<%= render 'form', user: @user %>
		</div>
	</div>
</div>

app/views/users/help.html.erb
<h4>見方</h4>

<table class="table table-bordered">
  <tr>
    <td align="center"><span class="glyphicon glyphicon-circle-arrow-down color-down"></span></td>
    <td>値下がりしています。今が買い時です！</td>
  </tr>
  <tr>
    <td align="center"><span class="glyphicon glyphicon-circle-arrow-up color-up"></span></td>
    <td>値上がりしています。もう少し辛抱しましょう</td>
  </tr>
  <tr>
  <td align="center"><span class="glyphicon glyphicon-circle-arrow-right color-right"></span></td>
  <td>前回から変わりありません</td>
  </tr>
</table>

<form class="text-center">
  <input type="button" name="button" value="このウィンドウを閉じる" onclick="window.close();" class="btn btn-default">
</form>

app/views/users/new.html.erb
<div class="row">
	<div class="col-xs-offset-3 col-xs-6">
		<div class="panel panel-default">
			<div class="panel-heading">ユーザ登録</div>
			<div class="panel-body">
				<%= form_for(@user) do |f| %>
					<div class="form-group">
						<%= f.label :name, 'お名前' %>
						<%= f.text_field :name, class:"form-control" %>
					</div>

					<div class="form-group">
						<%= f.label :email, 'メールアドレス' %>
						<%= f.email_field :email, class:"form-control" %>
					</div>

					<div class="form-group">
						<%= f.label :password, 'パスワード' %>
						<%= f.password_field :password, class:"form-control" %>
					</div>
					
					<div class="form-group">
						<%= f.label :password_confirmation, 'パスワード（確認）' %>
						<%= f.password_field :password_confirmation, class:"form-control" %>
					</div>
					
					<div class="text-right">
						<%= f.submit '登録する', class:"btn btn-success" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if false %>
#ユーザ情報の詳細画面
#本画面は、ユーザ画像とお気に入り登録された商品の一覧を表示する。
#ユーザ情報の編集、削除への画面遷移を持つ。
#お気に入り登録商品への画面遷移を持つ。
<% end %>

<div class="row">
	<div class="col-xs-3">
		<div class="user-profile">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="icon text-center">
						<img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
					</div>
				</div>
				<div class="panel-footer panel-custom">
					<div class="text-center">
						<h4><%= @user.name %>さん</h4>
					</div>
				</div>
			</div>
			<div class="text-center">
				<%= link_to '編集', edit_user_path, class:"btn btn-info" %>
				<%= link_to '退会', @user, method: :delete, data: {confirm: "登録されている情報が消えますが、よろしいですか?"}, class:"btn btn-danger" %>
			</div>
		</div>	
	</div>
	<div class="col-xs-9 item-table">
		<% if @items.count != 0 %>
			<table class="table table-striped">
				<thead class="table-edit">
					<tr>
						<th class="table1">商品名</th>
						<th class="table2">価格</th>
					</tr>
				</thead>
				<tbody>
					<% @items.each do |item| %>
						<tr>
							<td class="read-size"><%= link_to item.name, item %></td>
							<td>
								<%= latest_price_display(item) %>
								<%# 最新価格の方が安い場合 %>
								<% if (p = comparing_price(item)) == 0 %>
									<span class="glyphicon glyphicon-circle-arrow-down color-down"></span>
								<%# 最新価格の方が高い場合 %>
								<% elsif p == 1 %>
									<span class="glyphicon glyphicon-circle-arrow-up color-up"></span>
								<%# 最新価格に変化ない場合 %>
								<% else %>
									<span class="glyphicon glyphicon-circle-arrow-right color-right"></span>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="help">
				<%= link_to help_path, remote: true, :onclick=>"var w = ( screen.width-640 ) / 2; var h = ( screen.height-480 ) / 2; window.open(this.href,'XXX', 'height=480, width=640'+',left='+w+',top='+h);return false;" do %>
					<span class="glyphicon glyphicon-question-sign"></span>
					ヘルプ
				<% end %>
			</div>
			<div class="update-button">
				<%= form_tag(bulk_create_path) do %>
					<%= hidden_field_tag :items, @items %>
					<%= submit_tag '一括更新', class:"right-button btn btn-primary" , data: { confirm: "少し時間がかかりますが、よろしいですか?"} %>
				<% end %>
				<%= link_to '商品を追加', item_register_url_path, class:"btn btn-success" %>
				<%#= link_to '商品を追加', item_register_url_path, class:"btn btn-success", remote: true, :onclick=>"var w = ( screen.width-640 ) / 2; var h = ( screen.height-480 ) / 2; window.open(this.href,'XXX', 'height=480, width=640'+',left='+w+',top='+h);return false;" %>
			</div>
			<div>
				<%= paginate @items %>
			</div>
		<% else %>
		 <h4>商品が登録されていません</h4>
		 <div class="update-button">
		 	 <%= link_to '商品を追加', item_register_url_path, class:"btn btn-success" %>
		 </div>
		<% end %>
	</div>
</div>