config/routes.rb
Rails.application.routes.draw do
  #トップページ
  root to: 'toppages#index'
  
  #ユーザ登録関連
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #ログイン/ログアウト関連
  get 'signup', to: 'users#new'

  #ユーザ詳細　追加情報関連
  get 'users/help', to: 'users#help', as: 'help'
  get 'items/register', to:'items#item_register_url', as: 'item_register_url'
  post 'items/register', to:'items#item_register_info', as: 'item_register_info'
  
  resources :items, only:[:new, :show, :create]
  resources :users, only:[:show, :new, :create, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  post 'users/:id', to: 'items#bulk_create', as: 'bulk_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	validates :code, presence: true, length: { maximum: 255 }
	validates :name, presence: true, length: { maximum: 255 }
	validates :price, presence: true, length: { maximum: 255 }
	validates :url, presence: true, length: { maximum: 255 }
	validates :image_url, presence: true, length: { maximum: 255 }
	validates :company, presence: true, length: { maximum: 255 }

	has_many :ownerships
	has_many :users, through: :ownerships


<<-PAGE	
	def want?(item)
		self.find_by(code: @item.code)
	end

  def want(item)
    
  end
  
  def unwant(item)
  end
PAGE
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'uri'
  require 'open-uri'
  require 'json'

  def new
    @items = []
    
    @keyword = params[:keyword]
    
    if @keyword.present?
      #楽天API呼び出し
      rakuten
      #Yahoo! API呼び出し
      yahoo
    end

    @items = @items.sort{|a,b| a.price.to_i <=> b.price.to_i}
  end
  
  def create
    @item = Item.find_by(code: params[:item_code])

    @i = 0
    #更新用API呼び出し
    update_price
    
    if @i == 0
      @item.save
      #current_user.want(@item)
      flash[:success] = "価格情報を更新しました" 
    else
      flash[:warning] = "価格情報が更新できませんでした。商品が存在するか確認してください。"
    end
    redirect_back(fallback_location: root_url) 
  end
  
  def bulk_create
    @items = current_user.ownership_items
    @count = 0

    @items.each do |item|
      @item = Item.find_by(code: item.code)
      @i = 0

      #更新用API呼び出し
      update_price
      @count = @count + @i
      
      @item.save
      #current_user.want(@item)
    end

    if @count == 0
      flash[:success] = "価格情報を一括更新しました" 
    else
      flash[:warning] = "#{@i}件の更新ができませんでした"
    end
    redirect_back(fallback_location: root_url)
  end
  
  def show
    @item = Item.find(params[:id])
    
    person = Ownership.find_by_sql(["select count( distinct user_id ) as count from ownerships inner join items on ownerships.item_id in (select items.id from items where items.code = ?)", @item.code])
    @person_count = person[0].count
    #select count( distinct user_id ) as count from ownerships inner join items on ownerships.item_id in (select items.id from items where items.code = "cosme-venus:10001742");
    #u = Ownership.find_by_sql(["select count( distinct user_id ) as count from ownerships inner join items on ownerships.item_id in (select items.id from items where items.code = 'cosme-venus:10001742')"]) 
    #u[0].count
    
    #横軸
    #xAxis_categories = ['2013-11-09', '2013-11-10', '2013-11-11', '2013-11-12']
    xAxis_categories = []
    
    #横軸の間隔
    tickInterval = 1
    
    #縦軸
    #data = [120, 80, 90, 150]
    yAxis_data = []
    
    #results = current_user.ownership_items.where(code: @item.code)
    results = Item.where(code: @item.code)
    
    results.each do |result|
      xAxis_categories << result.created_at.strftime('%Y年%m月%d日')
      yAxis_data << result.price.to_i
    end
    
    #最新の7日間のみに整形
    xAxis_categories = xAxis_categories.last(7)
    yAxis_data = yAxis_data.last(7)

    @graph_data = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '価格推移')
      f.xAxis(categories: xAxis_categories, tickInterval: tickInterval)
      f.series(name: '価格推移', data: yAxis_data, type: 'spline')
      
      f.yAxis(title: {text: '円'})
    end
  end
  
  def item_register_url
    #render :layout => 'help_layout'
  end
  
  def item_register_info
    item_url = params[:"/items/register"][:item_url]
    @i = 0
    
    check = current_user.ownership_items.find_by(url: item_url)
    #binding.pry
    if check != nil
      flash[:warning] = "既に商品は登録されています"
      redirect_to user_path(current_user)
    else
      if item_url != "" && item_url.include?("farfetch.com")
        #@item = item_scraping(item_url)
        item_scraping(item_url)
        if @i == 0
          @item.save
          current_user.want(@item)
          flash[:success] = "商品を追加しました" 
        else
          flash[:warning] = "商品を追加できませんでした"
        end
        redirect_to user_path(current_user)
      elsif item_url.include?("https://quiet-meadow-28545.herokuapp.com/")
      
        #テスト用サイト
        if item_url.include?("static_image")
          item_scraping(item_url)
          @item.company = "テスト用サイト"
        elsif item_url.include?("variable_image")
          item_scraping(item_url)
          @item.company = "テスト用サイト"
        else
          @i = 1
        end
  
        if @i == 0
          @item.save
          current_user.want(@item)
          flash[:success] = "商品を追加しました" 
        else
          flash[:warning] = "商品を追加できませんでした(テスト)"
        end
        redirect_to user_path(current_user)
      else
        flash[:danger] = "商品を追加できませんでした。URLを確認して下さい。" 
        redirect_to user_path(current_user)
      end
    end
  end
  
  private
  
  def rakuten
    results = RakutenWebService::Ichiba::Item.search({
      keyword: @keyword,
      imageFlag: 1,
      hits: 20,
    })
    results.each do |result|
      item = Item.find_or_initialize_by(read_rakuten(result))
      @items << item
    end
  end
  
  def yahoo
    #APPIDをセット
    yahoo_application_id = ENV['YAHOO_APPID']
    
    #URL組み立て
    yahoo_url = "https://shopping.yahooapis.jp/ShoppingWebService/V1/json/itemSearch"
    yahoo_url = yahoo_url + "?appid=" + yahoo_application_id
    url = yahoo_url + "&query=" + @keyword + "&image_size=132" + "&hits=20"
    url = URI.encode(url)

    #HTTPS通信
    results_yahoo = JSON.parse(open(url).read, symbolize_names: true)
    
    #ハッシュから配列へ変換
    results_yahoo = results_yahoo[:ResultSet][:"0"][:Result].values
    
    #不要なキーを削除
    results_yahoo.shift
    results_yahoo.shift
    results_yahoo.pop 

    results_yahoo.each do |result|
      item = Item.find_or_initialize_by(read_yahoo(result))
      @items << item
    end
  end
  
  def update_price
    #binding.pry
    ##各社の商品検索APIを呼び出す
    if @item.company == "Yahoo!"
      #Yahoo!
      begin
        yahoo_application_id = ENV['YAHOO_APPID']
        yahoo_url = "https://shopping.yahooapis.jp/ShoppingWebService/V1/json/itemLookup"
        url = yahoo_url + "?appid=" + yahoo_application_id + "&itemcode=" + @item.code + "&image_size=132"
        result = JSON.parse(open(url).read, symbolize_names: true)
        @item = Item.new(read_yahoo_itemLookup_update(result))
        @i = 0
      rescue => e
      #rescue Mechanize::ResponseCodeError
        p e
        return @i = 1
      end
    elsif @item.company == "楽天"
      #楽天
      begin
        results = RakutenWebService::Ichiba::Item.search(itemCode: @item.code)
        @item = Item.new(read_rakuten(results.first))
        @i = 0
      rescue => e
      #rescue Mechanize::ResponseCodeError
        p e
        return @i = 1
      end
    elsif @item.company == "Farfetch"
      #Farfetch
      if Item.find_by(code: @item.code)
        #2回目以降
        item_scraping_continue(@item)
      else
        #初回登録時
        item_url = @item.url
        item_scraping(item_url)
      end
    elsif @item.company == "テスト用サイト"
      if Item.find_by(code: @item.code)
        #2回目以降
        item_scraping_continue(@item)
      else
        #初回登録時
        item_url = @item.url
        item_scraping(item_url)
      end
    end
    return @i
  end
  
  def item_scraping(item_url)
    #初回登録時
    @item = Item.new
    sleep(5)
    agent = Mechanize.new
    agent.user_agent_alias = 'Windows Mozilla'
    url = item_url

    #検証用URL
    #https://www.farfetch.com/jp/shopping/men/mostly-heard-rarely-seen---item-12324199.aspx?storeid=10421&rtype=certona_undefined&rpos=6
      p "URL set*************************"
      p Time.now.iso8601(3)
      p "********************************"

    begin
      #Item.first
      page = agent.get(url)
      
      p "URL get*************************"
      p Time.now.iso8601(3)
      p "********************************"
      sleep(5)

    rescue => e
      p e
      return @i = 1
    end

      p "URL parse***********************"
      p Time.now.iso8601(3)
      p "********************************"

    #初回登録時
    #商品名
    @item.name = page.search('//*[@id="slice-pdp"]/div/div[2]/div[3]/div[2]/span').text

    #code情報
    @item.code = "Farfetch" + "_" + @item.name

    #価格取得
    itemPrice = page.search('//*[@id="slice-pdp"]/div/div[2]/div[3]/div[3]/span/strong').text

    if itemPrice != ""
      @item.price = itemPrice.delete("¥").delete(",").strip.to_i
    else
      p "価格情報の取得に失敗しました。"
      return @i = 1
    end

    #URL
    #Webスクレイピング設定時に入力してもらうので再取得不要
    @item.url = item_url

    #会社名
    #Farfetchに設定
    @item.company = "Farfetch"
    
    #画像URL
    #@item.image_url = page.search("//*[contains(@class,'_5a7352')]/img").attribute('src').value

    begin
      value = page.search("//*[contains(@class,'_5a7352')]/img").attribute('src').value
    #rescue Mechanize::ResponseCodeError
    rescue => e
      p e
      p "画像取得に失敗しました。その1"
      return @i = 1
    end

    if value == nil
      #Item.first
      p "画像取得に失敗しました。その2"
        @item.image_url = ""
    else
      @item.image_url = value
    end

    #return @item
  end

  def item_scraping_continue(item)
    #2回目以降
    @item = Item.new
    
    agent = Mechanize.new
    agent.user_agent_alias = 'Windows Mozilla'
    url = item.url
    
    begin
      page = agent.get(url)
    #rescue Mechanize::ResponseCodeError
    rescue => e
      p e
      return @i = 1
    end

    #商品名
    @item.name = item.name

    #code情報
    @item.code = item.code

    #価格取得
    itemPrice = page.search('//*[@id="slice-pdp"]/div/div[2]/div[3]/div[3]/span/strong').text

    if itemPrice != ""
      @item.price = itemPrice.delete("¥").delete(",").strip.to_i
    else
      return @i = 1
    end
  
    #URL
    #Webスクレイピング設定時に入力してもらうので再取得不要
    @item.url = item.url

    #会社名
    #Farfetchに設定
    @item.company = "Farfetch"
    
    #画像URL
    @item.image_url = item.image_url

    return @item
  end
end

app/helpers/items_helper.rb
module ItemsHelper
	def register?(item)
		result = Item.find_by(code: item.code)
		
		if result
			return true
		else
			return false
		end
	end
end

app/views/items/_items.html.erb
<% if items %>
	<div class="row">
		<% items.each do |item| %>
			<div class="item">
				<div class="col-sm-3">
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<img src="<%= item.image_url %>" alt="no image">
						</div>
						<div class="panel-body">
							<% if current_user.want?(item) %>
								<p class="item-title"><%= link_to item.name, item %></p>
								<p><%= item.price %>円</p>
							<% else %>
								<p class="item-title"><%= item.name %></p>
								<p><%= item.price %>円</p>
							<% end %>
						</div>
						<div class="text-center">
							<% if logged_in? %>
								<%= render 'ownerships/want_button', item: item %>
							<% end %>
						</div>
						<div class="panel-footer text-center">
							<%= item.company %>
						</div>
					</div>
				</div>
			</div>
		<% end %>	
	</div>
<% end %>

app/views/items/_want_button.html.erb
<div class="want">
	
	<%# どうしても登録済みにならなかったのでとりあえず放置した。 %>
	<%# 後で見直す場合はownerships_controllerの部分の修正が必要。%>
		<%= form_tag(ownerships_path) do %>
			<%= hidden_field_tag :item_code, item.code %>
			<%= hidden_field_tag :type, 'Want' %>
			<%= submit_tag 'お気に入り登録', class:"btn btn-primary" %>
		<% end %>
	
	<% if false %>
	<%# if current_user.want?(item) %>
	<% if Item.find_by(code: item.code) %>
	<%# if register?(item) %>
	<%# お気に入り登録済みの場合 %>
		<%= form_tag(ownership_path(item.id), method: :delete) do %>
			<%= hidden_field_tag :item_id, item.id %>
			<%= hidden_field_tag :type, 'Want' %>
			<%= submit_tag 'お気に入り登録済み', class:"btn btn-success" %>	
		<% end %>
	<% else %>
	<%# お気に入り登録の場合 %>
		<%= form_tag(ownerships_path) do %>
			<%= hidden_field_tag :item_code, item.code %>
			<%= hidden_field_tag :type, 'Want' %>
			<%= submit_tag 'お気に入り登録', class:"btn btn-primary" %>
		<% end %>
	<% end %>
	<% end %>

</div>

app/views/items/item_register_url.html.erb
<div class="row">
	<div class="col-xs-offset-2 col-xs-8">
		<div class="panel panel-default">
			<div class="panel-heading">商品情報の登録</div>
        <div class="panel-body">
          <%= form_for(item_register_info_path) do |f| %>
        		<div class="form-group">
        			<%= f.label :item_url, "Farfetchの商品URLを設定してください" %>
        			<%= f.url_field :item_url, class:"form-control" %>
        		</div>
        		<p>Farfetchのサイトは<a href="https://www.farfetch.com/jp/shopping/men/items.aspx" target="_blank">こちら</a>です</p>
        		<div class="text-right">
        			<%#= f.submit '商品の追加', onclick="window.close();", class:"btn btn-success" %>
        			<%= f.submit '商品の追加', class:"btn btn-success", data: { confirm: "少し時間がかかりますが、よろしいですか?"}  %>
        		</div>
        	<% end %>
        </div>
		</div>
	</div>
</div>

app/views/items/new.html.erb
<div class="row">
	<div class="item-search">
		<div class="text-center">
			<%= form_tag(new_item_path, method: :get) do %>
				<div class="form-group">
					<%= text_field_tag :keyword, @keyword, class:"form-control", placeholder:"キーワードを入力して下さい", size:40%>
				</div>
				<%= submit_tag '商品を検索', class:"btn btn-success" %>
			<% end %>
		</div>
	</div>
</div>

<div>
	<%= render 'items', items: @items %>
</div>

app/views/items/show.html.erb
<%if false %>
#商品の詳細画面
#商品画像と商品へのリンク、価格情報のグラフを持つ
<% end %>

<div class="row">
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="item">
			<div class="panel panel-default">
				<div class="panel-heading text-center">
					<img src="<%= @item.image_url %>" alt="">
				</div>
				<div class="panel-body">
					<p class="item-title"><%= @item.name %></p>
				</div>
				<div class="text-center">
					<%= render 'ownerships/want_button', item: @item %>
				</div>
			</div>
		</div>
		<p class="text-center"><%= link_to "#{@item.company}詳細ページ", @item.url, target: '_blank', class:"btn btn-success"%></p>
	</div>
	
	<%# 価格チャートをここに載せる %>
	<div class="col-md-9 col-sm-6 col-xs-12">
		<%= high_chart("chart-1", @graph_data) %>
		<div>
			<span class="heart-custom glyphicon glyphicon-heart"><%= @person_count %></span>
			<span class="itme_show_font_size">※最新の7日間分を表示</span>
		</div>
		<div class="update-button">
			<%= form_tag(items_path) do %>
				<%= hidden_field_tag :item_code, @item.code %>
				<%= submit_tag '価格更新', class:"btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		toastr.options.timeOut = 3000; // 3秒
		
	toastr.options = {
	  "closeButton": true,
	  "debug": false,
	  "newestOnTop": false,
	  "progressBar": false,
	  "positionClass": "toast-top-center",
	  "preventDuplicates": false,
	  "onclick": null,
	  "showDuration": "300",
	  "hideDuration": "1000",
	  "timeOut": "5000",
	  "extendedTimeOut": "1000",
	  "showEasing": "swing",
	  "hideEasing": "linear",
	  "showMethod": "fadeIn",
	  "hideMethod": "fadeOut"
	}
	Command: toastr["info"]("<%= @person_count %>人がお気に入り登録をしています");
	});
</script>