config/routes.rb
Rails.application.routes.draw do
  #トップページ
  root to: 'toppages#index'
  
  #ユーザ登録関連
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #ログイン/ログアウト関連
  get 'signup', to: 'users#new'

  #ユーザ詳細　追加情報関連
  get 'users/help', to: 'users#help', as: 'help'
  get 'items/register', to:'items#item_register_url', as: 'item_register_url'
  post 'items/register', to:'items#item_register_info', as: 'item_register_info'
  
  resources :items, only:[:new, :show, :create]
  resources :users, only:[:show, :new, :create, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  post 'users/:id', to: 'items#bulk_create', as: 'bulk_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if message.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% message.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="navbar navbar-default">
	<div class="text-center">Product Search</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<!-- ログイン要否の判定 -->
				<% if logged_in? %>
					<%= link_to new_item_path do %>
						<div class="navbar-brand">
							<span class="glyphicon glyphicon-search"></span>
							Product Search
						</div>
					<% end %>
				<% else %>
					<%= link_to root_path do %>
						<div class="navbar-brand">
							<span class="glyphicon glyphicon-search"></span>
							Product Search
						</div>
					<% end %>				
				<% end %>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					
					<!-- ログイン要否の判定 -->
					<% if logged_in? %>
						<li>
							<%= link_to new_item_path do %>
								<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
								商品検索
							<% end %>
						</li>

						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<span class="gravatar">
									<img src="gravatar_url(current_user, size: 20)" alt="" class="img-circle">
								</span>
								<%= current_user.name %>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'マイページ', user_path(current_user) %></li>
								<li role="separator" class="divider"></li>
								<li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to '新規登録', signup_path %></li>
						<li><%= link_to 'ログイン', login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Product Search</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%#= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <% if false %>
    <script type="text/javascript" src="javascripts/footerFixed.js" 'data-turbolinks-track': 'reload'></script>
    <% end %>
    <%#= javascript_include_tag "footerFixed", 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <%= yield :cover %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/help_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Product Search</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="javascripts/footerFixed.js"></script>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    	<nav class="navbar navbar-default navbar-static-top">
    		<div class="container">
    			<div class="navbar-header">
    					<div class="navbar-brand">
    						<span class="glyphicon glyphicon-search">Product Search</span>
    					</div>
    			</div>
    		</div>
    	</nav>
    </header>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>